import = [
# "/Users/yuya-ito/.config/alacritty/themes/themes/tomorrow_night_bright.toml",
# "/Users/yuya-ito/.config/alacritty/themes/themes/wombat.toml",
# "/Users/yuya-ito/.config/alacritty/themes/themes/nightfox.toml",
  "/Users/yuya-ito/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "SauceCodePro NFP"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro NFP"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro NFP"
style = "Italic"

[font.normal]
family = "SauceCodePro NFP"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.9

[window.dimensions]
columns = 240
lines = 80
