unbind-key C-s
set-option -g prefix C-s

set-option -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'
set-option -sg escape-time 10
set-option -g focus-events on
set-option -g history-limit 100000

set-option -g status-position top

bind-key 'r' source-file ~/.tmux.conf \; display-message "reloaded configuration."

bind-key 'h' select-pane -L
bind-key 'j' select-pane -D
bind-key 'k' select-pane -U
bind-key 'l' select-pane -R

bind-key 'H' resize-pane -L 5
bind-key 'J' resize-pane -D 5
bind-key 'K' resize-pane -U 5
bind-key 'L' resize-pane -R 5

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind a setw synchronize-panes \; display "synchronize-panes #{?pane_synchronized,on,off}"

bind P run-shell "zsh -c ~/.config/tmux/popup.zsh"

# source-file ~/.config/tmux/themes/gruvbox.tmux

set -g @catppucin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# auto start terminal
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'wezterm'

# auto restore tmux
set -g @continuum-restore 'on'

# General statusline customisation
set -g status-style 'bg=terminal'

# Theme
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"

# status left style
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_mantle},bold]  #S },#{#[bg=#{@thm_mantle},fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_maroon}]  #{pane_current_command} "
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "

# status right style
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#{?#{e|>=:10,#{battery_percentage}},#{#[bg=#{@thm_red},fg=#{@thm_mantle}]},#{#[bg=#{@thm_mantle},fg=#{@thm_pink}]}} #{battery_icon} #{battery_percentage} "
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0}, none]│"
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0}, none]│"
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_blue}] 󰭦 %Y-%m-%d 󰅐 %H:%M "

# window style
set -wg automatic-rename on
set -g automatic-rename-format ''
# set -g window-status-separator '|'
set -g status-justify 'absolute-centre'
set -g @catppuccin_window_status_style 'custom'
set -g @catppuccin_window_flags ""
set -g @catppuccin_window_number ""
set -g @catppuccin_window_text "#[fg=#{@thm_rosewater},bg=#{@thm_mantle}] #I#{?#{!=:#{window_name},},: #W ,}"
set -g @catppuccin_window_current_number ""
set -g @catppuccin_window_current_text "#[fg=#{@thm_mantle},bg=#{@thm_peach}] #I#{?#{!=:#{window_name},},: #W ,}"

run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux
run ~/.config/tmux/plugins/tmux-cpu/cpu.tmux

bind-key 'C' run-shell "zsh -c ~/.config/tmux/select_theme.zsh"
